id: P196D6694
initial_creation_type: input
source_metadata:
  title: Tenth Pawo Rinpoche Series
  language: en
  description: 'Texts by and about the Tenth Pawo Rinpoche, Tsuklak Mawé Wangchuk
    (gtsug lag smra ba’i dbang phyug, 1912–1991):'
  volume:
    e78b2eac3b9a4def8aa30d8ac916a08d:
      title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
      parent: Guru Yoga
created_at: '2022-03-01T01:41:05.537773'
last_modified_at: '2022-03-01T01:41:05.537780'
